[package]
name = "yams_proto"
version = "0.1.0"
edition = "2021"

[dependencies]
flatbuffers = { git = "https://github.com/google/flatbuffers", tag = "v24.3.25" }

[build-dependencies]
flatbuffers-build = "*"
